import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import { config } from '../config';
import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import socketIOClient, { Socket } from 'socket.io-client';
import { generateUsername } from 'username-generator';

// console.log("config.ENDPOINT!", config.ENDPOINT!);


let socket: Socket;

const Home: NextPage = () => {

  useEffect(() => {
    socket = socketIOClient(config.ENDPOINT!);
  }, []);

  useEffect(() => {

    console.log("Called");

    socket.emit("CONNECT_USER", { data: generateUsername() });

    socket.on("DEVICE_DATA", ({ data }: any) => {
      console.log(data);
    });

    socket.on("LEAVE_USER", (user: any) => {
      console.log(user);
    });
  }, [socket])

  return (
    <div className={styles.container}>
      <Head>
        <title>Smart charging station | IOT final project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Smart Charging Station!
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
